library(ISLR)
set.seed(250)
numNBA <- nrow(nba)
nba_b <-sample(numNBA, numNBA/2)
regres_nba_b <- lm(Salary~.-Player -NBA_Country, nba, subset = nba_b)
resumen2<-summary(regres_nba_b)
attach(nba)
mean((Salary-predict(regres_nba_b, Auto))[-nba_b]^2)
glm_nba<-glm(Salary~.-Player -NBA_Country -Tm, nba, family = gaussian())
summary(glm_nba)
coef(glm_nba)
library(boot)
library(tinytex)

